export const images = {
  heart: require('../assets/images/heart.png'),
  heartFill: require('../assets/images/heart-fill.png'),
  triangle: require('../assets/images/triangle-right.png'),
  star: require('../assets/images/star.png'),
  starFill: require('../assets/images/starFill.png'),
  logo: require('../assets/images/logo.png'),
  logoFooter: require('../assets/images/logoFooter.png'),
  searchIcon: require('../assets/images/search-icon.png'),
  closeTextIcon: require('../assets/images/close-text.png'),
  searchTextIcon: require('../assets/images/search-icon-text.png'),
  filmBg: require('../assets/images/filmBgMock.png'),
  quote: require('../assets/images/quote.png'),
  filter: require('../assets/images/filter.png'),
};
