export const images = {
  heart: require('../assets/images/heart.png'),
  heartFill: require('../assets/images/heart-fill.png'),
  triangle: require('../assets/images/triangle-right.png'),
  logo: require('../assets/images/logo.png'),
  logoFooter: require('../assets/images/logoFooter.png'),
  searchIcon: require('../assets/images/search-icon.png'),
  closeTextIcon: require('../assets/images/close-text.png'),
  searchTextIcon: require('../assets/images/search-icon-text.png'),
  filmBg: require('../assets/images/filmBgMock.png'),
  quote: require('../assets/images/quote.png'),
  filter: require('../assets/images/filter.png'),
  star0: require('../assets/images/stars/star0.png'),
  star10: require('../assets/images/stars/star10.png'),
  star20: require('../assets/images/stars/star20.png'),
  star30: require('../assets/images/stars/star30.png'),
  star40: require('../assets/images/stars/star40.png'),
  star50: require('../assets/images/stars/star50.png'),
  star60: require('../assets/images/stars/star60.png'),
  star70: require('../assets/images/stars/star70.png'),
  star80: require('../assets/images/stars/star80.png'),
  star90: require('../assets/images/stars/star90.png'),
  star100: require('../assets/images/stars/star100.png'),
};
